### ISSUE TITLE
Create a selectable color palate 

### ISSUE THREAD

**Issue by aislinnjeske** [csu-hci-projects/MultiTouch-Media-v1.0#16]

**Comment by JustZack** [comment]
Record of idea I had so when i forget it i can come back here.

When the user rotates with 2 or 3 fingers open up a color wheel. The color wheel should start at the current color (I.E. 90 degrees on the unit circle is where their color is). continued rotation changes the color. Should also include a finite display of primary, and (recently) previously used colors.
